version: '3'
services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    labels:
      traefik.backend: "database"
      traefik.frontend.rule: "Host:database.localhost"

  # dbmanager:
  #   build: ./dbmanager
  #   container_name: dbmanager
  #   depends_on:
  #     - postgres
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./dbmanager/sources:/usr/src/app
  #   labels:
  #     traefik.backend: "dbmanager"
  #     traefik.frontend.rule: "Host:dbmanager.localhost"

  pgadmin:
    image: chorss/docker-pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:5050
    volumes:
      - ./pgadmin/data:/data
    labels:
      traefik.backend: "pgdamin"
      traefik.frontend.rule: "Host:pgdamin.localhost"
  # front:
  #   image: ./front/
  #   container_name: frontend
  #   labels:
  #     traefik.backend: "frontend"
  #     traefik.frontend.rule: "Host:frontend.local"

  back:
    build: ./back/
    container_name: backend
    depends_on:
      - postgres
    ports:
      - 3030:3000
    working_dir: /usr/src/app
    volumes:
      - ./back/sources:/usr/src/app
    labels:
      traefik.backend: "backend"
      traefik.frontend.rule: "Host:backend.local"

  traefik:
    image: traefik:1.5-alpine
    container_name: proxy
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "8080:80"
      - "8088:8080"
    volumes:
      # - ./proxy/conf/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml


